matrix:
  include:
    - language: go
      go: 
        - 1.9.x
        - release
        - tip
      install:
        - sudo apt-get install golang-go
      script:
        - go build code/life.go
        - go run code/life.go
    
    - language: ruby
      cache:
        - bundler
        - yarn
      services:
        - postgresql
      install:
        - sudo apt-get install ruby-full
      script:
        - ruby code/GameOfLife.rb

notifications:
  email: false