matrix:
  include:
    - language: go
      go: 
        - 1.9.x
        - release
        - tip
      install:
        - sudo apt-get install golang-go
      script:
        - go build code/life.go
        - go run code/life.go

notifications:
  email: false